reloj_checador/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users

  resources :companies
  resources :employees
  resources :attendances
  resources :reports

  get '/admin', to: 'admin#index'
  get '/month', :to => 'attendances#month'
  get "/average", :to=> 'attendances#average'

  root 'home#index'
end

reloj_checador/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reloj_checador/app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
 
  belongs_to :employee

  ransacker :created_at do
    Arel.sql('date(created_at)')
  end
  
end

reloj_checador/app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true

  has_many :employee, dependent: :destroy
end

reloj_checador/app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :position, presence: true
  validates :private_number, presence: true, uniqueness: true
  validates_numericality_of :private_number, message: 'Error Message'

  belongs_to :company
  has_many :attendance, dependent: :destroy
end

reloj_checador/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :employee
end

reloj_checador/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

reloj_checador/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

reloj_checador/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

reloj_checador/app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController

  def index
    @q = Attendance.ransack(params[:q])
    @attendances = @q.result(distinct: true)
    
  end

  def show; end

  def month
    @q = Attendance.ransack(params[:q])
    @attendances = @q.result(distinct: true)
    @asistencias = @q.result.count
  end  

  def average
    @average = Attendance.ransack(params[:q])
    @attendances = @average.result(distinct: true)
  end

  def new
    @attendances = Attendance.new
  end 

  def create
    if params[:commit] == "check-in" 
      if exist_params == true
      checkin
      end
    end
    if params[:commit] == "check-out"
      if exist_params == true
      checkout
      end
    end 
  end

  def exist_params
    begin
      @employee = Employee.find(attendances_params[:employee_id])
      return true
    rescue  => e
      redirect_to root_path, :notice => 'El ID no existe'
    end  
  end  

  def set_variables
    @find_attendances = Attendance.where(attendances_params).last
  end  

  def check_attendance
    set_variables.nil? || set_variables.checkin.strftime("%F") != Time.current.strftime("%F") 
  end  

  def checkin 
    @attendances = Attendance.where(attendances_params).last
    if @attendances.nil? || @attendances.checkin.strftime("%F") != Time.current.strftime("%F")
      @attendances = Attendance.create(attendances_params.merge(:checkin => Time.current))
      if @attendances.persisted?
        redirect_to root_path, :notice => "Checkin realizado correctamente"
      end
    else
      redirect_to root_path, :notice => "Ya hiciste el checkin"  
    end 
  end

  def checkout
    @attendances = Attendance.where(attendances_params).last
    if @attendances.nil? 
      redirect_to root_path, :notice => "Debes hacer el checkin primero"
    elsif @attendances.checkout.nil? || @attendances.checkout.strftime("%F") != Time.current.strftime("%F") 
      if @attendances.update(attendances_params.merge(:checkout => Time.current))
        redirect_to root_path, :notice => "Checkout realizado correctamente"
      end
    else 
      redirect_to root_path, :notice => "Ya hiciste el checkout"
    end
  end


  def filter
    if params[:commit] == "filtrar"
      month
    end
  end

  def filter_average   
    if params[:commit] == "filtrar"
      average
    end
  end
  
  

  private
  def attendances_params
    params.require(:attendance).permit(:checkin, :checkout, :employee_id)
  end
end

reloj_checador/app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @companies = Company.find(params[:id])
  end
  
  def new
    @companies = Company.new
  end 

  def create
    @companies = Company.create(company_params)
    if @companies.persisted?
      redirect_to companies_path
    end 
  end

  def edit
    @companies = Company.find(params[:id])
  end

  def update
    @companies= Company.find(params[:id])
    if @companies.update(company_params)
      redirect_to companies_path
    else
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    @companies= Company.find(params[:id])
    @companies.destroy
    redirect_to companies_path,
    status: :see_other
  end

  private
  def company_params
    params.require(:company).permit(:name,:address)
  end
end

reloj_checador/app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def index
    @employees = Employee.all
  end

  def show
    @employees = Employee.find(params[:id])
  end
  
  def new
    @employees = Employee.new
  end 

  def create
    @employees = Employee.create(employee_params)
    #@employees.user = current_user
    if @employees.persisted?
      redirect_to employees_path
    end 
  end

  def edit
    @employees = Employee.find(params[:id])
  end

  def update
    @employees= Employee.find(params[:id])
    if @employees.update(employee_params)
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    @employees= Employee.find(params[:id])
    @employees.destroy
    redirect_to employees_path,
    status: :see_other
  end

  private
  def employee_params
    params.require(:employee).permit(:name,:email, :position, :private_number, :company_id)
  end
end

reloj_checador/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

reloj_checador/app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def index
    @attendances = Attendance.all
  end
end

reloj_checador/app/helpers/admin_helper.rb
module AdminHelper
end

reloj_checador/app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

reloj_checador/app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

reloj_checador/app/views/admin/index.html.erb
<% if signed_in? && current_user.admin==true %>
  <div class="admin-home">
    <h1 class="admin-title">Panel de Administrador</h1>
    <%=button_to 'Ver Sucursales', '/companies',method: :get, class: 'button_e admin_button'%>
    <%=button_to 'Ver Empleados', '/employees',method: :get, class: 'button_e admin_button'%>
    <%=button_to 'Ver Reportes asistencia diaria', '/attendances',method: :get, class: 'button_e admin_button'%>
    <%=button_to 'Ver Reportes ausencia mensual', '/month',method: :get, class: 'button_e admin_button'%>
    <%=button_to 'Ver Reportes promedio de horas trabajadas', '/average',method: :get, class: 'button_e admin_button'%>
  </div>
<% else %>
  "No esta autorizado"
<% end %>

reloj_checador/app/views/attendances/average.html.erb
<% if signed_in? && current_user.admin==true %>
  <h1 class="title_empl"> Promedio de horas trabajadas</h1>

  <%= search_form_for @average, url: :average do |f|%>
    <div class="form-container">
      <div class="form-group">
        <div class="col-md-8 form-sub">
          <%= f.label 'id de empleado' %>
          <%= f.search_field :employee_id_eq %>
        </div>
      </div>
     
      <div class="form-group">
        <div class="col-md-8 form-sub">
          <%= f.label 'Desde' %>
          <%= f.search_field :created_at_eq%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-8 form-sub">
          <%= f.label 'Hasta' %>
          <%= f.search_field :created_at_lteq%>
        </div>
      </div>
      <div class="form-group">
          <div class="col-md-12 text-center" >
            <%= f.submit 'filtrar', class:"btn btn-primary btn-lg m-5" %>
          </div> 
      </div>
    </div>
  <%end%>

  <div class="container_table">
    <table class="table">
      <thead>
        <tr>
          <th scope="row" >Id de empleado</th> 
          <th scope="row" >checkin</th>
          <th scope="row" >checkout</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @attendances.each do |attendance| %>
          <tr>
            <td class="title"><%= attendance.employee_id %></td>
            <td class="title"><%= attendance.checkin.strftime("%F %H:%M:%S") if attendance.checkin.present?  %></td>
            <td class="title"><%= attendance.checkout.strftime("%F %H:%M:%S") if attendance.checkout.present?  %></td>
          </tr>
          <%end%>
        </tr>
    </tbody>
  </table>
  </div>


  <div class="container_table">
    <%@total_mes = 0%>
    <%@contador=0%>
    <table class="table">
      <thead>
        <tr>
          <th scope="row">Id de empleado</th>
          <th scope="row">dia</th>
          <th scope="row">Promedio del día</th> 
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @attendances.each do |attendance| %>
          <tr>
            <td><%= attendance.employee_id%>
            <td><%= attendance.created_at.strftime("%w : %b : %Y")%></td>
            
            <% if attendance.checkout.nil? %>
              <td>check incompleto</td>
            <%else%> 
              <% @h_i=attendance.checkin.strftime("%H").to_i*3600%>
              <% @m_i=attendance.checkin.strftime("%M").to_i*60%>
              <% @s_i=attendance.checkin.strftime("%S").to_i%>
              <% @total_i=@h_i+@m_i+@s_i%>
              <% @h_f=attendance.checkout.strftime("%H").to_i*3600%>
              <% @m_f=attendance.checkout.strftime("%M").to_i*60%>
              <% @s_f=attendance.checkout.strftime("%S").to_i%>
              <% @total_f=@h_f+@m_f+@s_f%>
              <% @total_d=@total_f-@total_i%>
              <% @total_mes= @total_d+@total_mes%>
              <% @total_h=@total_d/3600%>  
              <% @modulo= @total_d%3600%>
              <% @total_m=@modulo/60%>
              <% @modulo= @total_d%60%>
              <% @total_s=@modulo%>
              <% @contador += 1%>
              <td><%= "#{@total_h}:#{@total_m}:#{@total_s}" %></td>
            <%end%>
          </tr>
          <%end%>
        </tr>
    </tbody>
  </table>
 
  </div>
  <h3 class="title_empl">Promedio de horas trabajadas al mes</h3>
  <% @total_mes = @total_mes/@contador%>
  <% @total_h = @total_mes/3600%>  
  <% @modulo = @total_mes%3600%>
  <% @total_m=@modulo/60%>
  <% @modulo= @total_mes%60%>
  <% @total_s=@modulo%>
  <h4 class="title_empl"><%="#{@total_h}:#{@total_m}:#{@total_s}"%></h4>
  </br>
  </br>
  </br>
<%end%>

reloj_checador/app/views/attendances/index.html.erb
<% if signed_in? && current_user.admin==true %>
<h1 class="title_empl">Reporte de asistencia diaria</h1>

<%= search_form_for @q, url: :attendances do |f|%>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'id de empleado' %>
        <%= f.search_field :employee_id_eq %>
      </div>
    </div> 
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Fecha' %>
        <%= f.search_field :created_at_eq%>
      </div>  
    </div>   
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit 'filtrar', class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>


<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Id de empleado</th> 
        <th scope="row" >checkin</th>
        <th scope="row" >checkout</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @attendances.each do |attendance| %>
        <tr>
          <td class="title"><%= attendance.employee_id %></td>
          <td class="title"><%= attendance.checkin.strftime("%F %H:%M:%S") if attendance.checkin.present?  %></td>
          <td class="title"><%= attendance.checkout.strftime("%F %H:%M:%S") if attendance.checkout.present?  %></td>
        </tr>
        <%end%>
      </tr>
  </tbody>
</table>
</div>
<%end%>

reloj_checador/app/views/attendances/month.html.erb
<% if signed_in? && current_user.admin==true %>
<h1 class="title_empl">Reporte de ausencia mensual</h1>

<%= search_form_for @q, url: :month do |f|%>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'id de empleado' %>
        <%= f.search_field :employee_id_eq %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'desde' %>
        <%= f.search_field :created_at_gteq%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'hasta' %>
        <%= f.search_field :created_at_lteq%>
      </div>
    </div>       
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit 'filtrar', class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>


<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Id de empleado</th> 
        <th scope="row" >checkin</th>
        <th scope="row" >checkout</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <%@asistencias = 0%>
        <% @attendances.each do |attendance| %>
        <tr>
          <td class="title"><%= attendance.employee_id %></td>
          <td class="title"><%= attendance.checkin if attendance.checkin.present?  %></td>
          <td class="title"><%=  attendance.checkout if attendance.checkout.present?  %></td>
          <%if attendance.checkout.nil?%>
          <%else%>    
            <%@asistencias += 1%>  
          <%end%>   
        </tr> 
        <%end%>
      </tr>
    </tbody>
  </table>
</div>
<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Asistencia</th>
        <th scope="row" >Faltas</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="title"><%=   @asistencias %></td>
        <td class="title"><%=  20 - @asistencias   %></td> 
      </tr>
  </tbody>
</table>
</div>
<%end%>

reloj_checador/app/views/attendances/new.html.erb
<%= form_with scope: :attendance, url: attendances_path, method: :post do |f| %>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'id de empleado' %>
        <%= collection_select(:attendance, :employee_id, Employee.all , :id, :name, {}, {:multiple => false}) %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'fecha' %>
        <%= collection_select(:attendance, :checkin, Attendance.all , :checkin, :checkin, {}, {:multiple => false}) %>
      </div>
    </div>      
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit 'filtrar', class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>

reloj_checador/app/views/companies/_form.html.erb
<%=form_with model: @companies do |f| %>       
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Nombre' %>
        <%= f.text_field :name, class:"form-title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Dirección' %>
        <%= f.text_field :address, class:"form-title" %>               
      </div>
    </div>            
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit message, class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div>  
  </div>
<%end%>

reloj_checador/app/views/companies/edit.html.erb
<% if user_signed_in? && current_user.admin==true %>
  <%= render partial: 'form', locals: {message: 'Actualizar sucursal'}  %>
<% else %>
  "No esta autorizado"
<% end %>

reloj_checador/app/views/companies/index.html.erb
<% if signed_in? && current_user.admin==true %>
<h2 class="title_main">Sucursales</h2>
<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Nombre</th>
        <th scope="row" >Dirección</th>
        <th scope="row" >Id</th> 
        <th scope="row" colspan="2">Opciones</th> 
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @companies.each do |company| %>
        <tr>
          <td class="title"><%= company.name %></td>
          <td class="title"><%= company.address %></td>
          <td class="title"><%= company.id %></td>
          <td><%=button_to 'Editar', edit_company_path(company.id), method: :get, class: 'button_e'%></td>
          <td><%=button_to'Borrar', company_path(company.id), method: :delete, form: {data: {turbo_confirm: 'Estas seguro de eliminar esta sucursal?'}}, class: 'button_e'%></td>
        </tr>
        <%end%> 
      </tr>
    </tbody>
  </table>
</div>
<%=button_to 'Nueva sucursal', '/companies/new',method: :get, class: 'button_e new_Employees'%>
<% else %>
"No esta autorizado"
<% end %>

reloj_checador/app/views/companies/new.html.erb
<% if user_signed_in? && current_user.admin==true %>
  <%= render partial: 'form', locals: {message: 'Crear sucursal'}  %>
<% else %>
  "No esta autorizado"
<% end %>

reloj_checador/app/views/employees/_form.html.erb
<%=form_with model: @employees do |f| %>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Nombre' %>
        <%= f.text_field :name, class:"form-title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Email' %>
        <%= f.text_field :email, class:"form-title" %>
      </div>
    </div>      
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Posición' %>
        <%= f.text_field :position, class:"form-title" %>
      </div>
    </div>   
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'Número privado' %>
        <%= f.text_field :private_number, class:"form-title" %>
      </div>
    </div>
    <div class="form-group"> 
      <div class="col-md-8 form-sub"> 
        <%= f.label 'Sucursal' %>
        <%= collection_select(:employee, :company_id, Company.all, :id, :name, {}, {:multiple => false}) %>
      </div>
    </div> 
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit message, class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>

reloj_checador/app/views/employees/edit.html.erb
<% if user_signed_in? && current_user.admin==true %>
  <%= render partial: 'form', locals: {message: 'editar empleado'}  %>
<% else %>
  "No esta autorizado"
<% end %>

reloj_checador/app/views/employees/index.html.erb
<% if signed_in? && current_user.admin==true %>
<h1 class="title_empl">Empleados</h1>
<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Nombre</th>
        <th scope="row" >Email</th>
        <th scope="row" >Id</th> 
        <th scope="row" colspan="2">Opciones</th> 
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @employees.each do |employee| %>
        <tr>
          <td class="title"><%= employee.name %></td>
          <td class="title"><%= employee.email %></td>
          <td class="title"><%= employee.id %></td>
          <td><%=button_to 'Editar', edit_employee_path(employee.id), method: :get, class: 'button_e'%></td>
          <td><%=button_to'Borrar', employee_path(employee.id), method: :delete, form: {data: {turbo_confirm: 'Estas seguro de eliminar este empleado?'}}, class: 'button_e'%></td>
        </tr> 
        <%end%>
      </tr>
  </tbody>
</table>
</div>
<%=button_to 'Nuevo empleado', '/employees/new',method: :get, class: 'button_e new_Employees'%>
<% else %>
"No esta autorizado"
<% end %>

reloj_checador/app/views/employees/new.html.erb
<% if user_signed_in? && current_user.admin==true %>
<%= render partial: 'form', locals: {message: 'crear empleado'}  %>
<% else %>
"No esta autorizado"
<% end %>

reloj_checador/app/views/home/index.html.erb
<div>
  <div class= "watch_container">
    <h4 class="h4"> <%= Time.now.strftime("%F")%></h4>
    <h5 class="h5">Hora <%= Time.now.strftime("%H:%M:%S")%> </h5>
		<div class="form">
			<%= form_with scope: :attendance, url: attendances_path, local: true do |f| %>
				<%= f.text_field :employee_id,  placeholder: "numero de empleado", class:'text-field'%><br>
				<div class="button-container">
					<%= f.submit "check-in", class: 'button'%>
					<%= f.submit "check-out", class: 'button'%>
				</div>
			<%end%>
		</div>
	</div>
</div>

reloj_checador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reloj checador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">
    
    <header>
      <nav class="navbar ">
        <%= link_to root_path do%>
          <h1 class="watch-title" >Reloj checador</h1> 
        <%end%>
        <% if signed_in? %>
          <%=button_to 'Cerrar Sesión', destroy_user_session_path, class:'button_header button_off', method: :delete, form: {data: {turbo_confirm: 'Desea cerrar sesión?'}} %>
          <%=button_to 'Admin', '/admin',method: :get, class: 'button_header button_admin'%>
        <%else%>
        <%=button_to 'Registrarse',new_user_registration_path,method: :get, class: 'button_header'%> 
          <%=button_to 'Login',new_user_session_path, method: :get, class: 'button_header button_login'%>
        <% end %>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
  </body>
</html>

reloj_checador/app/views/reports/_form.html.erb
<%=form_with model: @reports do |f| %>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'reporte por dia' %>
        <%= f.text_field  class:"form-title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'fecha' %>
        <%= f.text_field , class:"form-title" %>
      </div>
    </div>      
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit message, class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>

reloj_checador/app/views/reports/index.html.erb
<% if signed_in? && current_user.admin==true %>
<h1 class="title_empl">Report</h1>


<%=form_with model: @reports do |f| %>
  <div class="form-container">
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'id de empleado' %>
        <%= collection_select(:attendance_day, :employee_id, Employee.all , :name, :id, {}, {:multiple => false}) %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 form-sub">
        <%= f.label 'fecha' %>
        <%= f.date_field :as_of_date%>
      </div>
    </div>      
    <div class="form-group">
      <div class="col-md-12 text-center" >
        <%= f.submit 'filtrar', class:"btn btn-primary btn-lg m-5" %>
      </div>
    </div> 
  </div>
<%end%>
<div class="container_table">
  <table class="table">
    <thead>
      <tr>
        <th scope="row" >Employee_id</th> 
        <th scope="row" >checkin</th>
        <th scope="row" >checkout</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @attendances.each do |attendance| %>
        <tr>
          <td class="title"><%= attendance.employee_id %></td>
          <td class="title"><%= attendance.checkin.strftime("%F %H:%M:%S") if attendance.checkin.present?  %></td>
          <td class="title"><%=  attendance.checkout.strftime("%F %H:%M:%S") if attendance.checkout.present?  %></td>         
        </tr> 
        <%end%>
      </tr>
  </tbody>
</table>
</div>
<%end%>